USE [master]
GO

/****** Object:  Database [CRUDEF]    Script Date: 06/13/2015 09:42:15 ******/
CREATE DATABASE [CRUDEF] ON  PRIMARY 
( NAME = N'CRUDEF', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\CRUDEF.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CRUDEF_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\CRUDEF_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CRUDEF] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CRUDEF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CRUDEF] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CRUDEF] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CRUDEF] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CRUDEF] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CRUDEF] SET ARITHABORT OFF 
GO

ALTER DATABASE [CRUDEF] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CRUDEF] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CRUDEF] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CRUDEF] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CRUDEF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CRUDEF] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CRUDEF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CRUDEF] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CRUDEF] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CRUDEF] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CRUDEF] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CRUDEF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CRUDEF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CRUDEF] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CRUDEF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CRUDEF] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CRUDEF] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CRUDEF] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CRUDEF] SET  READ_WRITE 
GO

ALTER DATABASE [CRUDEF] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CRUDEF] SET  MULTI_USER 
GO

ALTER DATABASE [CRUDEF] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CRUDEF] SET DB_CHAINING OFF 
GO

